name: Deploy to Amazon ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-1
  FRONTEND_ECR_REPOSITORY: ecs-training-container/myservice
  BACKEND_ECR_REPOSITORY: ecs-training-container/service-backend
  ECS_CLUSTER_NAME: ecs-training-container-stage-Cluster-NbCrZxfVhIdl
  FRONTEND_ECS_SERVICE_NAME: ecs-training-container-stage-myservice-Service-8vzB4vjoGhqa
  BACKEND_ECS_SERVICE_NAME: ecs-training-container-stage-service-backend-Service-me1TcDQFJMda

permissions:
  contents: read

jobs:
  build-and-push-frontend:
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.FRONTEND_ECR_REPOSITORY }}:latest ./myapp/frontend
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.FRONTEND_ECR_REPOSITORY }}:${{ github.sha }}
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.FRONTEND_ECR_REPOSITORY }}:latest

  build-and-push-backend:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest
    needs: build-and-push-frontend
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_ECR_REPOSITORY }}:latest ./myapp/backend
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_ECR_REPOSITORY }}:${{ github.sha }}
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_ECR_REPOSITORY }}:latest
        update-ecs-service:
          name: Update ECS Service
          runs-on: ubuntu-latest
          needs: [build-and-push-frontend, build-and-push-backend]
          steps:
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.AWS_REGION }}
          - name: Update ECS Service (Frontend)
            run: |
              aws ecs update-service --cluster ${{ env.ECS_CLUSTER_NAME }} --service ${{ env.FRONTEND_ECS_SERVICE_NAME }} --force-new-deployment
          - name: Update ECS Service (Backend)
            run: |
              aws ecs update-service --cluster ${{ env.ECS_CLUSTER_NAME }} --service ${{ env.BACKEND_ECS_SERVICE_NAME }} --force-new-deployment